export const USE_CASES = {
  'office-meetings': {
    slug: 'office-meetings',
    navLabel: 'Presentation Days',
    headline: 'Presentation Days.',
    label: 'Office & Meetings',
    subheading: 'Crisp structure that holds the drape. Looks senior-level from the first meeting to the last.',
    bodyCopy: 'The moment you walk into a room, the drape reads before you speak. Linen holds its structure across a full day - no sagging by 11am, no adjusting between back-to-back meetings. Structured for the room. Breathable enough for the heat, composed enough for the boardroom.',
    fabrics: ['Linen', 'linen'],
    metaTitle: 'Sarees for Office & Meetings | Neera',
    metaDescription: 'Shop Neera\'s linen sarees built for the office. Crisp drape, breathable fabric, office-ready from the first meeting to the last. Free shipping across India.',
    canonicalPath: '/for/office-meetings',
  },
  'everyday-work': {
    slug: 'everyday-work',
    navLabel: 'Everyday at Work',
    headline: 'Everyday at Work.',
    label: 'Everyday Wear',
    subheading: 'Feather-light. Breathable. Built for 8-hour days.',
    bodyCopy: 'Most sarees ask you to adjust to them. Mulmul adjusts to you. Feather-light cotton that moves the way you do throughout the day. Worn every day by women who have better things to manage.',
    fabrics: ['Mulmul', 'mulmul', 'Mul Mul Cotton', 'mul mul cotton'],
    metaTitle: 'Everyday Work Sarees | Neera',
    metaDescription: 'Shop Neera\'s Mulmul cotton sarees for working women. Feather-light, breathable, and comfortable across an 8-hour workday. Free shipping across India.',
    canonicalPath: '/for/everyday-work',
  },
  };
