export const USE_CASES = {
  'office-meetings': {
    slug: 'office-meetings',
    navLabel: 'Presentation Days',
    headline: 'Presentation Days.',
    label: 'Office & Meetings',
    subheading: 'Crisp structure that holds the drape. Looks senior-level from the first meeting to the last.',
    fabrics: ['Linen', 'linen'],
    metaTitle: 'Sarees for Office & Meetings | Neera',
    metaDescription: 'Shop Neera\'s linen sarees built for the office. Crisp drape, breathable fabric, office-ready from the first meeting to the last. Free shipping across India.',
    canonicalPath: '/for/office-meetings',
  },
  'everyday-work': {
    slug: 'everyday-work',
    navLabel: 'Everyday at Work',
    headline: 'Everyday at Work.',
    label: 'Everyday Wear',
    subheading: 'Feather-light. Breathable. Built for 8-hour days.',
    fabrics: ['Mulmul', 'mulmul', 'Mul Mul Cotton', 'mul mul cotton'],
    metaTitle: 'Everyday Work Sarees | Neera',
    metaDescription: 'Shop Neera\'s Mulmul cotton sarees for working women. Feather-light, breathable, and comfortable across an 8-hour workday. Free shipping across India.',
    canonicalPath: '/for/everyday-work',
  },
  'heritage-occasions': {
    slug: 'heritage-occasions',
    navLabel: 'Heritage Days',
    headline: 'Heritage Days.',
    label: 'Heritage & Occasions',
    subheading: 'Bold weaves. Deep heritage. Dressed for the room.',
    fabrics: ['Chettinad', 'chettinad'],
    metaTitle: 'Chettinad Sarees for Occasions | Neera',
    metaDescription: 'Discover Neera\'s Chettinad sarees. Bold traditional weaves with heritage structure — made for occasions that deserve it. Free shipping across India.',
    canonicalPath: '/for/heritage-occasions',
  },
};
